language: python
services:
  docker

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3.5

install:
  - pip install poetry tox

script:
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1 | sed 's/^py//'`
  # Here we build a wheel file for the project and have tox use that pre-built
  # package during testing. This ensures that we are testing all of the actual
  # deployment logic that may be customized in the actual wheel file
  - poetry build -f wheel
  - tox -e py$PYVER --installpkg ./dist/*.whl

# Deploy to test.pypi.org for branches
# Deploy to pypi.org for tags
# NOTE: You can not replace builds published to pypi, even if you delete one
#       so you must make sure your versions are always unique
jobs:
  include:
    - stage: deploy-release
      python: 3.6
      script:
        - poetry build -f wheel
        - poetry publish -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS true AND fork IS NOT true

    - stage: deploy-snapshot
      python: 3.6
      script:
        - poetry build -f wheel
        - poetry config repositories.dev https://test.pypi.org/legacy/
        - poetry publish -r dev -u $DEPLOY_USER -p $DEPLOY_PASS
      if: tag IS NOT true AND fork IS NOT true

after_success:
  - coveralls
