language: python

python:
  - "2.7"
  - "3.5"

script:
  - 'pip install tox'
  - 'tox'
  - 'if [ "$DEPLOY_USER" != "" && "$DEPLOY_PASS" != "" ]; then twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS; fi'