language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install tox twine wheel

script:
  - export PYVER=`echo $TRAVIS_PYTHON_VERSION | tr "." "\n" | head -n 1`
  - echo $PYVER
  - tox -e py$PYVER

#script:
#- 'pip install twine wheel'
#- 'python setup.py bdist_wheel'
#- 'if [[ "$DEPLOY_USER" != "" && "$DEPLOY_PASS" != "" ]]; then twine upload dist/*.whl -u $DEPLOY_USER -p $DEPLOY_PASS; fi'