name: Build Prerelease
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Static code analysis
        run: |
          tox -e py38-lint
      - name: Unit tests
        run: |
          # tox -e py38-test
          echo Fubar
      - name: Publish Pre-release
        run: |
          python -m pip install twine wheel
          python setup.py bdist_wheel
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*.whl -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_TOKEN }}

